### ISSUE TITLE
Incorporate new Esri "Add Data" widget

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EnviroAtlas#168]
Determine whether it will force us to upgrade to version 2.1 of the WAB.

**Comment by David-Yarnell** [comment]
I have tested adding the 'AddData' widget to all the version of the Web app builder. Initial results are that there are issues when adding this widget to a version prior to 2.0.   The errors in the console when adding the widget to an earlier version lead me to believe that it has to do with a change in ESRI's javascript API. The 'AddData' widget is utilizing VectorTileLayers which were not introduced until Esri javascript API version 3.15. This makes sense that it would not work in the EnviroAtlas application since it came from Web app builder 1.2 (Esri javascript API version 3.14). Looking to see if we can disable the portion to that adds a VectorTileLayers.

**Comment by torrin47** [comment]
Go ahead and upgrade JS API as far as possible - 15 or 17.

**Comment by torrin47** [comment]
Hrm - seems to do ok adding services from ArcGIS Online, but adding our own map services creates really funky names in the table of contents:
![image](https://cloud.githubusercontent.com/assets/2127036/17412443/c7122b50-5a4a-11e6-8975-3429c2dfcdde.png)
I'm also have a hard time using the search box - it seems like it's hovering in the wrong place and I can't enter any text into it.  Just me?
![image](https://cloud.githubusercontent.com/assets/2127036/17412484/f2601be6-5a4a-11e6-8f48-55cd1c562efa.png)

**Comment by David-Yarnell** [comment]
I'm seeing the numbers when adding a map service from URL. Then when I go back to search things seem out of place. Seem like there is some css issues.

**Comment by David-Yarnell** [comment]
I just noticed that the when adding a map service it only puts that number as the layer name in the layer list. In the legend it has the name and looks correct.
