### ISSUE TITLE
Fix issue where benefit categories spread out when community widget is enabled.

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EnviroAtlas#183]
It ends up looking like this:

![image](https://cloud.githubusercontent.com/assets/2127036/17254447/ecf53d98-5582-11e6-9f20-392828b1af38.png)

**Comment by Baohong** [comment]
The reason for the bug is that I copied the whole widget of "AddServcie", including css file, because there are similar radio button in that widget. Although I did not use the code/controls later, I forgot to delete the css file. There is a style definition for table and td in that file such as:
table{
  border-collapse: collapse;
}

td{
  padding-top: 10px;
  padding-left: 10px;
  font-size: small;
}
As soon as the widget (Select community or Add service) of such style definition is clicked by user, its style definition will be a global one. This might be a drawback of the whole Web app builder project and we should pay attention to. We should use a unique name to each control elements/classes specifically for each widget. That is, no widget should share their element / class names when it comes to style definition. 
Now the style definition to table and td has been removed from "SelectCommunity" widget and this bug is fixed. But if you click widget "AddService", same problem will appear. So David, could you make the style definition name "table" and "td" in file "AddService/css/style.css" more unique? like just define for class or a single element?
