### ISSUE TITLE
Add boundary selection widget

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EnviroAtlas#280]
Should be simplified version of SimpleSearchFilter - layer choices derived from config.json with hovertext and links to more info and checkboxes to add layers to the map, but no need for search/filter functionality.

Torrin needs to generate config.json.

**Comment by torrin47** [comment]
Didn't finish script for config.json, will complete on Monday.

**Comment by torrin47** [comment]
Completed, pull request submitted.

**Comment by Baohong** [comment]
Boundary layers widgets has been added. There are two problems:
1. The config file for boundary layers lacks eaLyrNum on some of its layers.
2. There is no title for boundary layers on legend. Could we make it similar to the community layers so that each symbol has its name and could appear on legend?
