### ISSUE TITLE
Ensure check boxes in simpleSearchFilter widget correspond to whether layers are on map

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EnviroAtlas#301]
The checkbox next to a layer title in the simpleSearchFilter widget may be used to add or remove that layer from the Layer List widget, but if the list of layers shown in simpleSearchFilter changes (using topics, geographies, and Search) the checkbox is cleared, and no longer reflects whether that layer has already been added to the map.  Can we fix this so that the checkbox next to a layer in simpleSearchFilter consistently reflects whether that layer has been added to the map through all searches and filters?

**Comment by Baohong** [comment]
Does this mean that if topic changes---say if  a user toggles on one topic, select some layers. Should those selected layers be removed when he toggles off this topic?
Is that is the requirement, then what if the user just wants to add layers one topic after one topic? If I am a user, I might want to toggle on just one topic, see what's inside, select some layers. Next I toggle off that topic, change to another topic and select/add some more layers. I do not want to remove all the layers I have selected before.
Please make more clarification.

**Comment by torrin47** [comment]
No. Just because a layer doesn't appear in the list of simpleSearchFilter results doesn't mean it is removed from the map.  It just means that it's not appearing in the results.  If it re-appears in the simpleSearchFilter results from a different search or a topic being turned on and off, though, the checkbox next to it should reflect whether it has already been added to the map.

**Comment by Baohong** [comment]
Done. 

I have also examined the speed of how selectable layers in SimpleSearchFilter respond to topics toggled on and off. After modifying small part of code, I do not feel much delay in most cases. But a significant delay happens when user toggles off all topics or else toggles on just one topic.

The reason for this delay is that I cannot modify place holder in text search box once DataTable is constructed. So if place holder need a change (transitioned between "Search selected topics" and "Search all layers"), I have to delete whole datatable and reconstruct, populate a new datatable.
