### ISSUE TITLE
Text change/addition for Select community widget 

### ISSUE THREAD

**Issue by brosenbaum** [Innovate-Inc/EnviroAtlas#366]
Annie requested to... Please use the following text for the community selection widget.  The first two sentences should be bolded. 

"**Select one community below or choose “combined communities”. This affects how the legend and map will display.** 
Selecting one community will calculate the legend based on the values for that community only.  Selecting combined communities will calculate the legend based on the values for all communities. Return to this menu at any time to change your selection."

This will replace the short sentences we have now.

**Comment by brosenbaum** [comment]
Jeremy has some of this done. he will push that code.

**Comment by Baohong** [comment]
Two communities CleOH and MSPMN are added to community selection widget.
I noticed that there is a file "nationalmetadata.json" in folder scripts. Our current EnviroAtlas only address community layers for metadata link. Later, I will work on this file so that there will be metadata link for each added nation layers also.
