### ISSUE TITLE
When the searchFilter sidebar is closed and re-opened, map zooms to home extent

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EnviroAtlas#373]
This is pretty clearly an unintended side-effect of the code that zooms the map to the initial extent on pageload.  We probably need to make that function into a run-once that unhooks from the triggering event after it's been performed.

**Comment by Baohong** [comment]
This issue is caused by my modification to the code while I was working for issue "After the page loads trigger 'home' button function  #330". Every time the SimpleSearchFilter is opened, map will zoom to whole extent. I will try to modify code again so that it will be triggered only one the widget is loaded.

**Comment by Baohong** [comment]
Done.
