### ISSUE TITLE
If a community is already in the view extent when that community is selected, it doesn't get re-rendered with the new symbology until the extent changes.

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EnviroAtlas#415]
Or if the layer is toggled on and off.  Maybe we could address this by comparing the view extent with the community extent and refreshing the layer if they overlap?

**Comment by Baohong** [comment]
It is the "setVisibility(false)" and "setVisibility(true)" cause the problem. I removed the two lines and now it is working on leb. But since we incorporated legend into layerlist, the new incormporated legend does not refresh with pre-defined symbology. User has to turn off and on layer to refresh legend.

So I might have to add "setVisibility(false)" and "setVisibility(true)" back to refresh legend and use zoom-in/zoom-out in code to force showing layers.

**Comment by Baohong** [comment]
Legend itself refreshes according to pre-symology. Only legend in LayerList widget has refreshing problem.
