### ISSUE TITLE
Community location dot comments

### ISSUE THREAD

**Issue by brosenbaum** [Innovate-Inc/EnviroAtlas#451]
- [x] Community locations dot layer doesn't appear if you select Estimated [land cove type] in stream buffer (percent) layers (first 4 layers under Land Cover: Near Water) . Have not tested for all other "tiled" services. 
- [x] Need the community location to display for some of the PBS layers. Any that are **not national** in scale.
- [x] Communities dot doesn't go away when you zoom in to community - **_need to discuss what is wanted here_**
- [x] When you turn on the community boundaries layer from boundaries, it turns into the community dots as you zoom out, but they aren't clickable - confusing? **_need to discuss what is wanted here_**

**Comment by torrin47** [comment]
Decision on community dots...  When a community layer is selected, rather than adding just the dot layer as a feature service, the full map service with both dots and boundaries should be added (with the existing scale breaks between the two).  Also, all dots should be a single size - no need for two different sized dots.

**Comment by brosenbaum** [comment]
did you want me to start with the service changes?

**Comment by torrin47** [comment]
Sure, I believe that can happen at any time, but it'd be helpful, thanks!

**Comment by brosenbaum** [comment]
republished with scale dependencies
