### ISSUE TITLE
Time Series Viewer updates

### ISSUE THREAD

**Issue by brosenbaum** [Innovate-Inc/EnviroAtlas#459]
- [x] could initial click open window that gives "about" info and then allows user to link to tool?

for the current FSViewer... 
- [x] would like the Time Slider Scenario Box to have the following text in it
 "Scenario _X_ - RCP _X_, _Season or Annual Variable_ (units)"
 So for example, it would look like this:
 "Scenario II (RCP 4.5), Summer Maximum Temperature (Degrees F)"

- [x] Can we also add the following text to a box below the legend:
"Climate scenarios provide likely approximations of future conditions given a set of initial assumptions and model results. The future is inherently uncertain with no guarantee that these scenarios reflect what will occur at the specified future time."

**Comment by brosenbaum** [comment]
Annie is reviewing all text in the widget, but felt these changes were ready to include.

**Comment by Baohong** [comment]
Item #1: We can show a normal window like all other widget window and inside show a link which could be directed to FSViewer.

Item #2: Which is Time Slider Scenario Box? Is it "Scenario Information" at top right of map?

Item #3: Because the limitation of real estate of the legend area ---- could we add the text inside of  "Scenario Information" which is at top right of map, so that user could see the whole legend without using scroll bar when the "Scenario Information" accordion is folded?

**Comment by brosenbaum** [comment]
for the first item, lets discuss this tomorrow on the call. I think I agree with Sue that it would be good to warn folks that another window will open.

For the second item, yes, it is the box on the top of the right panel.

for the third item, Sounds like a great idea - let's verify with Annie tomorrow on the call.

**Comment by torrin47** [comment]
Annie says yes on #1

**Comment by Baohong** [comment]
done.
