### ISSUE TITLE
Onclick event not working for dynamicLayer popups or HUC Nav/Raindrop tools

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EnviroAtlas#495]
After incorporating the popup window function, Map click checks the pop info. But when there is no layers, layer id is undefined.

**Comment by Baohong** [comment]
HUC Nav and Raindrop tools are working on Leb. I had hoped that the fix also works for the issues in dynamicLayer popups. It seems that dynamicLayer popups issues and HUC Nav issues are not the same cause. 

I have never tested dynamicLayer popups before. This is how I test on dynamicLayer popups ---check on topic "Wetlands and Lowlands", then check on layer "Potential Wetland Area", Pop window should work for this layer.

Let me know if that is a correct way to test dynamicLayer popups.

I would like to debug dynamicLayer popups issues, but would appreciate a previous github code edition which works for dynamicLayer popups. I have downloaded the previous code from https://github.com/Innovate-Inc/EnviroAtlas/tree/d4f180eaffece6b9886cd80c3dcda6cd982b4682. But dynamicLayer popups does not works for that code either.  Or else maybe I tested in the wrong way, Torrin, could you let me know which layer I should test against? Which github code works for dynamic layer popup so that I could compare with?
