### ISSUE TITLE
Allow attribute table to be shown for map services.

### ISSUE THREAD

**Issue by torrin47** [Innovate-Inc/EnviroAtlas#75]
Asking EPA about what attributes should be included/shown in the attribute table viewer.  Possibilities include all attributes, only the attribute used to symbolize the layer, thematically similar attributes, or just the attributes of layers that have been added to the active layerlist.

**Comment by brosenbaum** [comment]
Found this old issue... seems to be the discussion today adt the end of the call (2/16/2017). Still up for discussion.

Can we add one table each for EnviroAtlas metrics for communities and national (rather than basically the same table for each layer) and turn on from the list of active layers? Also, could this allow user to add more if they want? through the show/hide? there are other tables, but these aren't the "metrics".

Depending on decision - may have to update attributes displayed in the services.

**Comment by torrin47** [comment]
Believe this issue is closed? Attribute tables are live and satisfactory to users. Can revisit if users have feedback, otherwise closing.
